# Generated by Django 6.0.1 on 2026-01-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_location_remove_ad_city_remove_ad_location_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'), ('choice', 'Choice')], max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.RemoveField(
            model_name='ad',
            name='brand',
        ),
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_properties', to='ads.category')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.property')),
            ],
            options={
                'verbose_name_plural': 'Category Properties',
                'unique_together': {('category', 'property')},
            },
        ),
        migrations.CreateModel(
            name='AdPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='ads.ad')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.property')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('category_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='ads.categoryproperty')),
            ],
            options={
                'verbose_name_plural': 'Category Property Values',
                'unique_together': {('category_property', 'value')},
            },
        ),
    ]
