# Generated by Django 6.0.1 on 2026-01-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_property_remove_ad_brand_categoryproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproperty',
            name='parentProperty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ads.categoryproperty'),
        ),
    ]
