# Generated by Django 6.0.1 on 2026-01-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_categoryproperty_parentproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproperty',
            name='parentProperty',
        ),
        migrations.AddField(
            model_name='categorypropertyvalue',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_values', to='ads.categoryproperty'),
        ),
        migrations.AddField(
            model_name='categorypropertyvalue',
            name='depends_on_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.categorypropertyvalue'),
        ),
    ]
