# Generated by Django 6.0.1 on 2026-01-22 11:02

from django.db import migrations
from django.conf import settings

def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model('accounts', 'Profile')
    
    users_without_profile = User.objects.filter(profile__isnull=True)
    profiles_to_create = []
    for user in users_without_profile:
            profiles_to_create.append(Profile(user=user))
    
    Profile.objects.bulk_create(profiles_to_create)
    print(f'Created {len(users_without_profile)} profiles')


def reverse_create_profiles(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_users, reverse_create_profiles),
    ]

