# Generated by Django 6.0.1 on 2026-01-20 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid international phone number.', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
    ]
